### ISSUE TITLE
Error CS0176: Member 'ImagesClass.ImagesLoaded' cannot be accessed with an instance reference; qualify it with a type name instead

### ISSUE THREAD

**Issue by pjlplourde** [WWPowell-ga/WPFMultiImage#1]
On Build, a fatal error with Code CS0176 and Description "Member 'ImagesClass.ImagesLoaded' cannot be accessed with an instance reference; qualify it with a type name instead" shows up in WPFMultiImage\slnWPFMultiImage\WPFMultiImage\MainCode.cs at Line 13 Column 9.

**Comment by WWPowell-ga** [comment]
Thanks for letting me know. I'm not code complete yet. I know it doesn't work.Should I have waited to update GitHub until it did?Or mentioned that on Twitter?-Wm
    On Friday, January 14, 2022, 12:12:07 PM EST, Pierre Plourde ***@***.***> wrote:  
 
 


On Build, a fatal error with Code CS0176 and Description "Member 'ImagesClass.ImagesLoaded' cannot be accessed with an instance reference; qualify it with a type name instead" shows up in WPFMultiImage\slnWPFMultiImage\WPFMultiImage\MainCode.cs at Line 13 Column 9.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pjlplourde** [comment]
I would not have committed code that didn't build. Keep in mind that if you scaffold out a method but can't get to the actual meat of it, you can just say "throw new NotImplementedException()" and your code will build just fine. No need to wait for it to run to commit, but it should at least build, generally, at least in my opinion.
