### ISSUE TITLE
Right Sidebar Resizing Issue

### ISSUE THREAD

**Issue by westbrookmd** [WWPowell-ga/WPFMultiImage#2]
![WPFMultiImageRoadmap](https://user-images.githubusercontent.com/71563811/150162125-d2bfa181-676f-42b0-b955-79a85a3da751.gif)
The stats and palette sidebar doesn't adjust according to the window size. This makes viewing the image difficult in a window that isn't maximized.

The workaround that I used is to hide the stats once I am not in a maximized screen.

Maybe the stats and palette sidebar could be ".2*" with a scroll viewer (or something along those lines)?

**Comment by WWPowell-ga** [comment]
After trying several solutions will leave as is
