### ISSUE TITLE
Image File Name Saves as Full File Path By Default

### ISSUE THREAD

**Issue by westbrookmd** [WWPowell-ga/WPFMultiImage#5]
When saving images on my computer I noticed that the default name for files is the full containing folder's path (in addition to the original image's name).

Save File Dialog opens in the correct directory, but the file name it's attempting to save as is the full directory.

Current Behavior: Saving as file name "C:\Programming\WPFMultiImage\slnWPFMultiImage\WPFMultiImage\bin\Debug\net5.0-windows\Capture.tif"

Expected Behavior: Saving as file name "Capture.tif"

**Comment by WWPowell-ga** [comment]
Fixed
